version: "3.3"
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "30100:5432"
    environment:
      POSTGRES_USER: knst
      POSTGRES_PASSWORD: knst
      POSTGRES_DB: knst
  mail:
    image: reachfive/fake-smtp-server
    ports:
      - "30200:1025"
      - "30201:1080"
