spring:
  datasource:
    username: knst
    password: knst
    url: jdbc:postgresql://localhost:30100/knst
  mail:
    host: localhost
    port: 30200


server:
  port: 30000

logging:
  level:
    org.springframework.security: DEBUG
